version: "2"
services:
  nodejs:
    image: bastilimbach/docker-magicmirror
    ports:
      - "8080:8080"
    volumes:
      - "./web/nodejs/config:/opt/magic_mirror/config"
      - "./web/nodejs/modules:/opt/magic_mirror/modules"



# docker run  -d \
# 	--publish 80:8080 \
# 	--restart always \
# 	--volume ~/magic_mirror/config:/opt/magic_mirror/config \
# 	--volume ~/magic_mirror/modules:/opt/magic_mirror/modules \
# 	--name magic_mirror \
# 	bastilimbach/docker-magicmirror


  # command: bash -c "npm install && node ./dist/index.js"


  # to start: docker-compose up

  # Docker Commands:
    # command: node ./dist/index.js
    # docker stop $(docker ps -a -q)
    # docker rm $(docker ps -a -q)
    # docker rmi $(docker images -a -q)

# Example of working host code
# sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /Users/james.miller/docker/var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://10.9.126.211:8080/v1/scripts/E018295D1CF4082B7B23:1483142400000:53rurIg4AdrJNHK0MQF1SFILGE
